import { describe, it } from 'node:test';

import { RuleTester } from 'eslint';

import rule from '../no-unreachable-disabled-tooltip.js';

// RuleTester looks for global `describe`/`it`; under `node --test` they are importable but not
// global, so hand them over explicitly — otherwise every case collapses into one opaque file-level
// failure instead of being reported per case.
RuleTester.describe = describe;
RuleTester.it = it;

const ruleTester = new RuleTester({
  languageOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

// Any path outside components/ui/, where the rule deliberately stands down.
const APP_FILE = '/repo/apps/web/src/app/(app)/admin/phase-catalog/page.tsx';

ruleTester.run('no-unreachable-disabled-tooltip', rule, {
  valid: [
    {
      name: 'the sanctioned wrapper: span carries tabIndex, so the trigger is reachable',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex" tabIndex={0}>
              <Button disabled>Elimina</Button>
            </span>
          </TooltipTrigger>
        );
      `,
    },
    {
      name: 'tabIndex bound to an expression counts — a control disabled only while loading needs the span in the tab order only then',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex" tabIndex={isLoading ? 0 : -1}>
              <Button disabled={isLoading}>Elimina</Button>
            </span>
          </TooltipTrigger>
        );
      `,
    },
    {
      name: 'nothing disabled anywhere: an enabled button is its own tab stop',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <Button onClick={onDelete}>Elimina</Button>
          </TooltipTrigger>
        );
      `,
    },
    {
      name: 'without asChild the trigger renders its own element, so the child is not the trigger',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger>
            <Button disabled>Elimina</Button>
          </TooltipTrigger>
        );
      `,
    },
    {
      name: 'shadcn primitives are vendor files, regenerated by the CLI',
      filename: '/repo/apps/web/src/components/ui/sidebar.tsx',
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <button disabled>x</button>
          </TooltipTrigger>
        );
      `,
    },
    {
      name: 'a control disabled behind a spread stays invisible to a syntactic rule',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex">
              <Button {...rest}>Elimina</Button>
            </span>
          </TooltipTrigger>
        );
      `,
    },
  ],

  invalid: [
    {
      // The shape that actually shipped in four files: the span is there, the tabIndex is not,
      // so the control is greyed out and the explanation reaches nobody using a keyboard.
      name: 'span without tabIndex around a disabled button',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span>
              <Button disabled={!canWrite}>Elimina</Button>
            </span>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'unreachable' }],
    },
    {
      // A transiently disabled control is unreachable exactly during the window in which the
      // user wonders why it does not respond.
      name: 'dynamic disabled counts as disabled',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex">
              <Button disabled={isLoading}>Salva</Button>
            </span>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'unreachable' }],
    },
    {
      // The disabled control need not be the span's direct child: any wrapper markup in between
      // leaves the trigger just as unreachable.
      name: 'disabled control nested deeper in the trigger subtree',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex">
              <div className="flex gap-2">
                <button type="button" disabled={!canUpdate}>Solo Uomo</button>
              </div>
            </span>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'unreachable' }],
    },
    {
      // Distinct message: here tabIndex is not the fix. A disabled element is not focusable no
      // matter what tabIndex says, so the trigger has to move onto a wrapper.
      name: 'the trigger is itself the disabled element',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <Button disabled>Elimina</Button>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'selfDisabled' }],
    },
    {
      // tabIndex on a disabled element is the plausible wrong fix — it looks like the sanctioned
      // pattern and changes nothing, so the rule must not accept it.
      name: 'tabIndex on the disabled trigger itself does not make it focusable',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <Button disabled tabIndex={0}>Elimina</Button>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'selfDisabled' }],
    },
    {
      // tabIndex={-1} is the plausible wrong fix on the wrapper: it looks like the sanctioned
      // pattern, and Tab skips a negative tabIndex exactly as it skips no tabIndex at all.
      name: 'a permanently negative tabIndex leaves the wrapper out of the tab order',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex" tabIndex={-1}>
              <Button disabled={!canWrite}>Elimina</Button>
            </span>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'negativeTabIndex' }],
    },
    {
      // The shape the gender toggles have: the disabled controls exist only inside a `.map`, so a
      // check that walks literal children alone never sees them.
      name: 'disabled controls produced by a map are still disabled controls',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            <span className="inline-flex">
              <div className="flex gap-2">
                {GENDER_OPTIONS.map(o => <button key={o} type="button" disabled={!canUpdate}>{o}</button>)}
              </div>
            </span>
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'unreachable' }],
    },
    {
      // A trigger whose child arrives through an expression container renders one element per
      // branch, and each branch is a trigger that has to stand on its own.
      name: 'every branch of a conditional child is checked',
      filename: APP_FILE,
      code: `
        const A = () => (
          <TooltipTrigger asChild>
            {canWrite ? <Button onClick={onDelete}>Elimina</Button> : <span><Button disabled>Elimina</Button></span>}
          </TooltipTrigger>
        );
      `,
      errors: [{ messageId: 'unreachable' }],
    },
  ],
});
