SELECT BLACQDF00198315.EANCODELETTORETXT, Item.No_, Item.[MODEL ITEM NO_], Item.[VARIABLE CODE 01] AS COLOR, Item.[VARIABLE CODE 02] AS [SIZE], Sum(1) AS QTY_LETTURE
FROM BLACQDF00198315 LEFT JOIN (EANCodes_CleanDoubled_PerBLAC LEFT JOIN Item ON EANCodes_CleanDoubled_PerBLAC.[Item No_] = Item.No_) ON BLACQDF00198315.EANCODELETTORETXT = EANCodes_CleanDoubled_PerBLAC.[Cross-Reference No_]
GROUP BY BLACQDF00198315.EANCODELETTORETXT, Item.No_, Item.[MODEL ITEM NO_], Item.[VARIABLE CODE 01], Item.[VARIABLE CODE 02];

