SELECT NoteOrdiniVenditaGlobale.CodiceCliente, NoteOrdiniVenditaGlobale.ordinamentocommento, NoteOrdiniVenditaGlobale.Commento
FROM NoteOrdiniVenditaGlobale
ORDER BY NoteOrdiniVenditaGlobale.CodiceCliente, NoteOrdiniVenditaGlobale.ordinamentocommento;

