SELECT Sum(NSP_StoricoFattClientiAgenti.ImpProvvFatturato) AS ImpProvvFatturato, NSP_StoricoFattClientiAgenti.TipoDocumento, NSP_StoricoFattClientiAgenti.NrDocumento, NSP_StoricoFattClientiAgenti.CodiceAgente, NSP_StoricoFattClientiAgenti.PercentualeProvvigione, NSP_StoricoFattClientiAgenti.RaggrStampe, NSP_StoricoFattClientiAgenti.DataLiquidazione
FROM NSP_StoricoFattClientiAgenti
GROUP BY NSP_StoricoFattClientiAgenti.TipoDocumento, NSP_StoricoFattClientiAgenti.NrDocumento, NSP_StoricoFattClientiAgenti.CodiceAgente, NSP_StoricoFattClientiAgenti.PercentualeProvvigione, NSP_StoricoFattClientiAgenti.RaggrStampe, NSP_StoricoFattClientiAgenti.DataLiquidazione;

