SELECT TabellaAppoggioSovraccolliDaLetture.Cartone, Sum(TabellaAppoggioSovraccolliDaLetture.Pezzi) AS SommaDiPezzi
FROM TabellaAppoggioSovraccolliDaLetture
GROUP BY TabellaAppoggioSovraccolliDaLetture.Cartone;

