SELECT ListaPerSovraccolluDaLetture.CARTONE, Format$([EANCODELETTORE],"0") AS EANCODELETTORETXT, Count(ListaPerSovraccolluDaLetture.EANCODELETTORE) AS Pezzi, Format$([EANCODELETTORE],"0000000000000") AS EANCODELETTORETXT_OLD
FROM ListaPerSovraccolluDaLetture
GROUP BY ListaPerSovraccolluDaLetture.CARTONE, Format$([EANCODELETTORE],"0"), Format$([EANCODELETTORE],"0000000000000");

