SELECT tempiPagBaseDocumentiDaVerificareConDoppi.ChiaveMovimentoFatturaNotaCredito, Count(tempiPagBaseDocumentiDaVerificareConDoppi.ChiaveMovimentoPagamento) AS ConteggioDiChiaveMovimentoPagamento
FROM tempiPagBaseDocumentiDaVerificareConDoppi
GROUP BY tempiPagBaseDocumentiDaVerificareConDoppi.ChiaveMovimentoFatturaNotaCredito;

