SELECT tempiPagBaseDocumentiDaVerificareQueryGenerale.ChiaveMovimentoFatturaNotaCredito, Sum([importopagato]) AS importototalePagatoPerEntry, First(tempiPagDocumentiCalcoloDelloImporto.Importo) AS ImportoOriginalePerEntry
FROM tempiPagBaseDocumentiDaVerificareQueryGenerale INNER JOIN tempiPagDocumentiCalcoloDelloImporto ON tempiPagBaseDocumentiDaVerificareQueryGenerale.ChiaveMovimentoFatturaNotaCredito = tempiPagDocumentiCalcoloDelloImporto.[Entry No_]
GROUP BY tempiPagBaseDocumentiDaVerificareQueryGenerale.ChiaveMovimentoFatturaNotaCredito;

