SELECT VenditeAssortimentoArticoloModelloVeloce_step0.Marchio, VenditeAssortimentoArticoloModelloVeloce_step0.Stagione, VenditeAssortimentoArticoloModelloVeloce_step0.mesegiorno, Sum(VenditeAssortimentoArticoloModelloVeloce_step0.ValueSold) AS ValueSold, Sum(VenditeAssortimentoArticoloModelloVeloce_step0.qty) AS qty
FROM VenditeAssortimentoArticoloModelloVeloce_step0
GROUP BY VenditeAssortimentoArticoloModelloVeloce_step0.Marchio, VenditeAssortimentoArticoloModelloVeloce_step0.Stagione, VenditeAssortimentoArticoloModelloVeloce_step0.mesegiorno;

